import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="Thierno",
  password="Wtbgroup35@1",
  database="DWH"
)
# print(mydb)

mycursor = mydb.cursor()


# mycursor.execute("""CREATE TABLE DWH_D_E_COMMERCE_CLIENT (ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY, TEL_CLIENT VARCHAR(255), NOM_CLIENT VARCHAR(255), E_MAIL_CLIENT VARCHAR(255),
#                  ADRESS_CLIENT VARCHAR(255), COMMENTAIRE_CLIENT VARCHAR(255));""")

# mycursor.execute("""CREATE TABLE DWH_D_E_COMMERCE_PRODUIT(ID_PRODUIT INT AUTO_INCREMENT PRIMARY KEY, CODE_PRODUIT VARCHAR(255),
#                 MARQUE_PRODUIT VARCHAR(255), PRIX_PRODUIT FLOAT);""")

# mycursor.execute("""CREATE TABLE DWH_D_E_COMMERCE_LIVRAISON(ID_LIVRAISON INT NOT NULL AUTO_INCREMENT PRIMARY KEY, DATE_LIVRAISON TIMESTAMP,
#                  PRIX_LIVRAISON FLOAT(2), SOCIETE_LIVRAISON VARCHAR(255));""")

# mycursor.execute("""CREATE TABLE DWH_D_E_COMMERCE_BOUTIQUE(ID_BOUTIQUE INT NOT NULL AUTO_INCREMENT PRIMARY KEY, NUM_COMMANDE_BOUTIQUE VARCHAR(255),
#                 NOM_BOUTIQUE VARCHAR(255));""")

# mycursor.execute("""CREATE TABLE D_DATE(DATE_JOUR DATE PRIMARY KEY, ANNEE YEAR, MOIS VARCHAR(255), JOUR VARCHAR(255), LE_JOUR INT);""")

mycursor.execute("""CREATE TABLE DWH_F_E_COMMERCE_COMMANDES(ID_COMMANDE INT AUTO_INCREMENT PRIMARY KEY, DATE_COMMANDE DATE, ID_BOUTIQUE INT, ID_CLIENT INT, ID_PRODUIT INT,  
                NUM_COMMANDE VARCHAR(255), PRIX_COMMANDE FLOAT, NOMBRE_ARTICLE INT, ID_LIVRAISON INT,
                FOREIGN KEY(DATE_COMMANDE) REFERENCES D_DATE(DATE_JOUR),  FOREIGN KEY(ID_BOUTIQUE) REFERENCES DWH_D_E_COMMERCE_BOUTIQUE(ID_BOUTIQUE), 
                FOREIGN KEY(ID_CLIENT) REFERENCES DWH_D_E_COMMERCE_CLIENT(ID_CLIENT), FOREIGN KEY(ID_PRODUIT) REFERENCES DWH_D_E_COMMERCE_PRODUIT(ID_PRODUIT),
                FOREIGN KEY(ID_LIVRAISON) REFERENCES DWH_D_E_COMMERCE_LIVRAISON(ID_LIVRAISON));""")

table = mycursor.execute("SHOW TABLES")
print(table)